version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./infrastructure/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: pm
